name: Auto test for sealos rootfs
on:
  workflow_dispatch:
jobs:
  install-sealos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trace memory
        run: |
          wget https://github.com/labring/sealos/releases/download/v4.3.3/sealos_4.3.3_linux_amd64.tar.gz
          tar -zxf  sealos_4.3.3_linux_amd64.tar.gz sealos 
          chmod a+x sealos
          ./sealos version
          cd k3s && cp -rf  ../registry/ . && cd ..
          ./sealos images
          cd k3s && mkdir -p bin && wget https://github.com/k3s-io/k3s/releases/download/v1.27.4%2Bk3s1/k3s &&  chmod a+x k3s && mv k3s bin/k3s &&  cd ..
          cd k3s && sed -i 's#v1.25.13#v1.25.13-amd64#g' Kubefile && cd ../
          cd k3s && ../sealos build -t xxx . && cd ../
          ./sealos images
  

  install-sealos-by-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trace memory
        run: |
          wget https://github.com/labring/sealos/releases/download/v4.3.3/sealos_4.3.3_linux_amd64.tar.gz
          tar -zxf  sealos_4.3.3_linux_amd64.tar.gz sealos 
          chmod a+x sealos
          ./sealos version
          cd k3s && cp -rf  ../registry/ . && cd ..
          ./sealos images
          cd k3s && mkdir -p bin && wget https://github.com/k3s-io/k3s/releases/download/v1.27.4%2Bk3s1/k3s-arm64 && chmod a+x k3s-arm64 && mv k3s-arm64 bin/k3s && cd ..
          cd k3s && sed -i 's#v1.25.13#v1.25.13-arm64#g' Kubefile && cd ../
          cd k3s && ../sealos build -t xxx-arm64 . && cd ../
          ./sealos images

