name: keep-commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "sealos-ci-robot@sealos.io"
          git config --local user.name "sealos-ci-robot"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.G_SYNC_ALIYUN_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push